services:
  - type: web
    name: gas-generator
    runtime: node
    plan: standard
    buildCommand: npm ci && npm run build
    startCommand: node --expose-gc --max-old-space-size=1536 node_modules/.bin/next start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1536"
      - key: PORT
        value: "10000"
    healthCheckPath: /api/health
    autoDeploy: true
